providers:
  - airtap-sauce

browsers:
  - name: chrome for android
    version: 10

presets:
  local:
    providers:
      - airtap-playwright
    browsers:
      - name: chromium
      - name: firefox
